<a href="https://colab.research.google.com/github/AngelTroncoso/Data_Science/blob/main/5_Pandas_Distintos_Formartos_de_Archivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Leyendo Archivos CSV

###Importando Archivos

In [6]:
import pandas as pd

df = pd.read_csv('/content/superstore_data.csv')
df.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [19]:
datos_punto_coma = pd.read_csv('/content/superstore_data_punto_coma.csv', sep = ";")
datos_punto_coma.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [21]:
numeros_de_filas = pd.read_csv('/content/superstore_data.csv', nrows= 5)
numeros_de_filas

Id  Year_Birth   Education Marital_Status  Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced   84835        0         0   
1      1        1961  Graduation         Single   57091        0         0   
2  10476        1958  Graduation        Married   67267        0         1   
3   1386        1967  Graduation       Together   32474        1         1   
4   5371        1989  Graduation         Single   21474        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [22]:
n_de_columnas = pd.read_csv('/content/superstore_data.csv', usecols=["Id","Year_Birth","Income"])
n_de_columnas

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [23]:
n_de_columnas_n = pd.read_csv('/content/superstore_data.csv', usecols=[0,1,4])
n_de_columnas_n

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

##**Guardar archivos en csv**

In [24]:
n_de_columnas_n.to_csv('n_de_columnas_n.csv')

In [25]:
clientes = pd.read_csv('/content/n_de_columnas_n.csv')
clientes.head()

Unnamed: 0     Id  Year_Birth   Income
0           0   1826        1970  84835.0
1           1      1        1961  57091.0
2           2  10476        1958  67267.0
3           3   1386        1967  32474.0
4           4   5371        1989  21474.0

##**Guardar datos sin indices**

In [26]:
n_de_columnas_n.to_csv('n_de_columnas_n.csv', index=False)

In [27]:
n_de_columnas_n = pd.read_csv('/content/n_de_columnas_n.csv')
n_de_columnas_n.head()

Id  Year_Birth   Income
0   1826        1970  84835.0
1      1        1961  57091.0
2  10476        1958  67267.0
3   1386        1967  32474.0
4   5371        1989  21474.0

#**Desafío: leyendo datos con múltiples parámetros:**

####**Su desafío aquí será leer este archivo usando la función read_csv de la biblioteca Pandas. Se deben agregar algunos parámetros para que la lectura se realice correctamente. Entonces, aquí hay algunos consejos:**

In [28]:
import chardet

In [33]:
with open('/content/datos_sus.csv', 'rb') as file:
    print(chardet.detect(file.read()))

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}


In [35]:
datos = pd.read_csv('/content/datos_sus.csv', encoding='ISO-8859-1', sep=';', skiprows=3, skipfooter = 9, engine='python')

In [36]:
datos.head(9)

Unidade da Federação     2008/Jan     2008/Fev     2008/Mar     2008/Abr  \
0             Rondônia   1388528,39   2931283,42   1541682,52   1525314,96   
1                 Acre    902416,00   1497206,26   1794028,48   1730469,42   
2             Amazonas   4735529,42   7118990,57   8196635,49   8259378,42   
3              Roraima    657889,53    777939,31    718688,03    839994,39   
4                 Pará  18864744,11  19553758,20  21937342,70  20842829,69   
5                Amapá   1120973,34   1268740,33    974651,24   1141137,32   
6            Tocantins   3441592,69   4985688,85   6205612,60   4984482,09   
7             Maranhão  10723506,39  13559679,41  13985142,36  14809416,46   
8                Piauí   7985142,43  10079928,25  10298372,45  10775976,33   

      2008/Mai     2008/Jun     2008/Jul     2008/Ago     2008/Set  ...  \
0   1645953,84   1406150,68   3065279,01   3231494,61   3117178,63  ...   
1   1819443,92   1828496,00   2511754,59   2089107,14   2275708,53  ...   
2   7831399,90   8477273,62   9368858,72   9352532,70   9363099,35  ...   
3    862347,96    832440,66    996693,09    894271,18    910424,17  ...   
4  23249952,88  23240687,56  24002223,56  23341218,03  25172261,32  ...   
5    866346,18   1440978,95   1426659,48   1475551,38   1651341,43  ...   
6   5511002,46   4927934,22   5445602,28   5413710,38   5596669,50  ...   
7  14505727,38  14908091,32  15784899,40  15195312,89  14951277,75  ...   
8  10398360,88  10528253,88  11040107,92  10549176,40  10899198,97  ...   

      2020/Jul     2020/Ago     2020/Set     2020/Out     2020/Nov  \
0  11824687,13  11733307,76  10201985,14   7955139,45   9357946,29   
1   3915193,20   3640142,82   3391242,21   4044321,44   3276590,10   
2  19769460,14  18059931,43  17841015,63  16408315,10  19895617,91   
3   3015488,30   2826486,18   2928043,91   3090313,73   3621031,05   
4  40804126,43  44385715,88  36820249,47  36965931,34  39004315,80   
5   3253399,45   2946398,44   2416019,23   2203732,04   2218532,26   
6   9155572,36   8390267,72   8729632,49   7770885,66    527840,46   
7  35473489,49  32219037,29  30077152,72  33200778,47  31942670,33   
8  19908573,27  25663537,49  20230782,72  22389215,72  18911604,50   

      2020/Dez     2021/Jan     2021/Fev     2021/Mar          Total  
0   8880836,55   9266014,59   7730597,04  11023309,47   996411254,68  
1   3696997,31   3715723,12   3538427,92   4077045,92   450048530,47  
2  17765167,69  21430289,17  25917134,55  22032176,22  1917247936,05  
3   3454460,94   3266928,47   3519773,73   3985530,08   328876965,09  
4  38015145,79  38354682,46  37688314,23  33276392,89  4705309002,29  
5   2566919,60   2802886,34   2817849,31   3188210,98   309860092,59  
6    675277,05    419553,49    319160,87   1357751,33  1020028272,64  
7  30783403,58  30738750,31  30924484,99  39663677,48  3871069498,04  
8  20883972,79  22689390,32  19400269,01  20018325,75  2280888802,74  

[9 rows x 161 columns]

##**Para saber más: error de codificación - ¿cómo solucionarlo?**

###**Giovanna es una científica de datos que trabaja en una empresa de comercio electrónico. Ella es responsable de analizar datos de ventas para identificar patrones y tendencias que puedan ayudar a la empresa a tomar decisiones informadas.Recientemente, le asignaron una nueva tarea: analizar un archivo CSV que contiene información sobre las ventas de la empresa durante un período determinado. Para ello, Giovanna intentó leer un archivo CSV en Google Colab, usando la biblioteca Pandas con el siguiente comando:

In [37]:
#import pandas as pd
#df = pd.read_csv('datos.csv')

In [38]:
import chardet

In [39]:
#with open('datos.csv', 'rb') as file:
#    print(chardet.detect(file.read()))

In [40]:
{'encoding': 'UTF-16', 'confidence': 1.0, 'language': ''}

{'encoding': 'UTF-16', 'confidence': 1.0, 'language': ''}

In [41]:
#df = pd.read_csv('datos.csv', encoding='UTF-16')

###**Aula N°2 Trabajando con archivos de Excel**

In [44]:
emisiones = pd.read_excel('/content/emisiones_CO2.xlsx')
emisiones

País ISO 3166-1 alpha-3   Año         Total        Carbón  \
0      Afganistán                AFG  1750  0.000000e+00           NaN   
1      Afganistán                AFG  1751  0.000000e+00           NaN   
2      Afganistán                AFG  1752  0.000000e+00           NaN   
3      Afganistán                AFG  1753  0.000000e+00           NaN   
4      Afganistán                AFG  1754  0.000000e+00           NaN   
...           ...                ...   ...           ...           ...   
63099      Global                WLD  2017  3.609674e+10  1.450697e+10   
63100      Global                WLD  2018  3.682651e+10  1.474683e+10   
63101      Global                WLD  2019  3.708256e+10  1.472598e+10   
63102      Global                WLD  2020  3.526409e+10  1.417456e+10   
63103      Global                WLD  2021  3.712385e+10  1.497960e+10   

             Aceite           Gas       Cemento        Quema        Otros  \
0               NaN           NaN           NaN          NaN          NaN   
1               NaN           NaN           NaN          NaN          NaN   
2               NaN           NaN           NaN          NaN          NaN   
3               NaN           NaN           NaN          NaN          NaN   
4               NaN           NaN           NaN          NaN          NaN   
...             ...           ...           ...          ...          ...   
63099  1.224263e+10  7.144928e+09  1.507923e+09  391992176.0  302294047.0   
63100  1.226602e+10  7.529847e+09  1.569218e+09  412115746.0  302478706.0   
63101  1.234565e+10  7.647528e+09  1.617507e+09  439253991.0  306638573.0   
63102  1.119181e+10  7.556290e+09  1.637538e+09  407583673.0  296301685.0   
63103  1.183716e+10  7.921829e+09  1.672592e+09  416525563.0  296145746.0   

       Per Capita  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             NaN  
...           ...  
63099   4749682.0  
63100   4792753.0  
63101   4775633.0  
63102   4497423.0  
63103   4693699.0  

[63104 rows x 11 columns]

Examinar archivo excele con sus hojas

In [46]:
# Examinar archivo excele con sus hojas
pd.ExcelFile('/content/emisiones_CO2.xlsx').sheet_names

['emisiones_C02', 'emisiones_percapita', 'fuentes']

In [47]:
percapita = pd.read_excel('/content/emisiones_CO2.xlsx', sheet_name='emisiones_percapita')
percapita.sample(5)

País ISO 3166-1 alpha-3   Año  Total  Carbón  Aceite  Gas  \
38255     Namibia                NAM  1925    NaN     NaN     NaN  NaN   
29278      Kuwait                KWT  1924    NaN     NaN     NaN  NaN   
12090  Islas Cook                COK  1872    NaN     NaN     NaN  NaN   
4431   Bangladesh                BGD  1829    NaN     NaN     NaN  NaN   
35454  Mauritania                MRT  1844    NaN     NaN     NaN  NaN   

       Cemento  Quema  Otros  
38255      NaN    NaN    NaN  
29278      NaN    NaN    NaN  
12090      NaN    NaN    NaN  
4431       NaN    NaN    NaN  
35454      NaN    NaN    NaN

In [49]:
Fuentes = pd.read_excel('/content/emisiones_CO2.xlsx', sheet_name='fuentes')
Fuentes.sample(5)

País ISO 3166-1 alpha-3   Año       Total  \
38098                 Namibia                NAM  1768      [NONE]   
52769  San Cristóbal Y Nieves                KNA  1751      [NONE]   
28167               Kazajstán                KAZ  1901      [NONE]   
21727                 Hermoso                GHA  1989  CDIAC 2022   
33648                  Malaui                MWI  1942      [NONE]   

           Carbón      Aceite         Gas        Cemento       Quema   Otros  \
38098      [NONE]      [NONE]      [NONE]         [NONE]      [NONE]  [NONE]   
52769      [NONE]      [NONE]      [NONE]         [NONE]      [NONE]  [NONE]   
28167      [NONE]      [NONE]      [NONE]         [NONE]      [NONE]  [NONE]   
21727  CDIAC 2022  CDIAC 2022  CDIAC 2022  Andrew cement  CDIAC 2022  [NONE]   
33648      [NONE]      [NONE]      [NONE]         [NONE]      [NONE]  [NONE]   

                         Per Capita  
38098                        [NONE]  
52769                        [NONE]  
28167                        [NONE]  
21727  CDIAC 2022 and UN population  
33648                        [NONE]

In [50]:
intervalo_columna = pd.read_excel('/content/emisiones_CO2.xlsx', sheet_name='emisiones_C02', usecols= 'A:D')
intervalo_columna.sample(5)

País ISO 3166-1 alpha-3   Año       Total
44549   Portugal                PRT  1963  10011581.0
22721  Guadalupe                GLP  1895         0.0
861      Andorra                AND  1795         0.0
3322     Austria                AUT  1808         0.0
56404         Ir                TGO  1850         0.0

In [51]:
intervalo_fila = pd.read_excel('/content/emisiones_CO2.xlsx', sheet_name='emisiones_C02', usecols= 'A:D', nrows = 10)
intervalo_fila

País ISO 3166-1 alpha-3   Año  Total
0  Afganistán                AFG  1750      0
1  Afganistán                AFG  1751      0
2  Afganistán                AFG  1752      0
3  Afganistán                AFG  1753      0
4  Afganistán                AFG  1754      0
5  Afganistán                AFG  1755      0
6  Afganistán                AFG  1756      0
7  Afganistán                AFG  1757      0
8  Afganistán                AFG  1758      0
9  Afganistán                AFG  1759      0

###Excel Google sheet

In [52]:
sheet_id = '1scFa_6PJ1EsXHh3iuflm0P0dJ3Auy4nOzBrYMLP4Mfw'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [53]:
datos_sheet = pd.read_csv(url)
datos_sheet.head()

País ISO 3166-1 alpha-3   Año Total Carbón Aceite  Gas Cemento Quema  \
0  Afganistán                AFG  1750     0    NaN    NaN  NaN     NaN   NaN   
1  Afganistán                AFG  1751     0    NaN    NaN  NaN     NaN   NaN   
2  Afganistán                AFG  1752     0    NaN    NaN  NaN     NaN   NaN   
3  Afganistán                AFG  1753     0    NaN    NaN  NaN     NaN   NaN   
4  Afganistán                AFG  1754     0    NaN    NaN  NaN     NaN   NaN   

  Otros Per Capita  
0   NaN        NaN  
1   NaN        NaN  
2   NaN        NaN  
3   NaN        NaN  
4   NaN        NaN

In [54]:
sheet_id = '1scFa_6PJ1EsXHh3iuflm0P0dJ3Auy4nOzBrYMLP4Mfw'
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet=emisiones_percapita'

In [55]:
percapita_sheet = pd.read_csv(url_percapita)
datos_sheet.head()

País ISO 3166-1 alpha-3   Año Total Carbón Aceite  Gas Cemento Quema  \
0  Afganistán                AFG  1750     0    NaN    NaN  NaN     NaN   NaN   
1  Afganistán                AFG  1751     0    NaN    NaN  NaN     NaN   NaN   
2  Afganistán                AFG  1752     0    NaN    NaN  NaN     NaN   NaN   
3  Afganistán                AFG  1753     0    NaN    NaN  NaN     NaN   NaN   
4  Afganistán                AFG  1754     0    NaN    NaN  NaN     NaN   NaN   

  Otros Per Capita  
0   NaN        NaN  
1   NaN        NaN  
2   NaN        NaN  
3   NaN        NaN  
4   NaN        NaN

In [56]:
sheet_id = '1scFa_6PJ1EsXHh3iuflm0P0dJ3Auy4nOzBrYMLP4Mfw'
url_fuente = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet=fuentes'

In [57]:
fuente_sheet = pd.read_csv(url_fuente)
fuente_sheet.tail()

País ISO 3166-1 alpha-3   Año                                 Total  \
63099  Global                WLD  2017  CDIAC 2022, BP, and Sum of countries   
63100  Global                WLD  2018  CDIAC 2022, BP, and Sum of countries   
63101  Global                WLD  2019  CDIAC 2022, BP, and Sum of countries   
63102  Global                WLD  2020  CDIAC 2022, BP, and Sum of countries   
63103  Global                WLD  2021  CDIAC 2022, BP, and Sum of countries   

                  Carbón             Aceite                Gas        Cemento  \
63099  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63100  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63101  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63102  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63103  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   

                    Quema   Otros  \
63099  CDIAC 2022 and GCP  [NONE]   
63100  CDIAC 2022 and GCP  [NONE]   
63101  CDIAC 2022 and GCP  [NONE]   
63102  CDIAC 2022 and GCP  [NONE]   
63103  CDIAC 2022 and GCP  [NONE]   

                                              Per Capita  
63099  CDIAC 2022, BP, Sum of countries, and UN popul...  
63100  CDIAC 2022, BP, Sum of countries, and UN popul...  
63101  CDIAC 2022, BP, Sum of countries, and UN popul...  
63102  CDIAC 2022, BP, Sum of countries, and UN popul...  
63103  CDIAC 2022, BP, Sum of countries, and UN popul...

##**Publicado en la web**

solo una hoja no requiere autentificaciòn

In [58]:
import pandas as pd

url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQQYIkYwPDBFtO2rvldVvllxY8mAHoyjrLWN1nzKAgClqnzareaFmQjlJ4cpv7c7UWym8SjdgOSxBlG/pub?output=csv'
df = pd.read_csv(url)
df.head()


País ISO 3166-1 alpha-3   Año Total Carbón Aceite  Gas Cemento Quema  \
0  Afganistán                AFG  1750     0    NaN    NaN  NaN     NaN   NaN   
1  Afganistán                AFG  1751     0    NaN    NaN  NaN     NaN   NaN   
2  Afganistán                AFG  1752     0    NaN    NaN  NaN     NaN   NaN   
3  Afganistán                AFG  1753     0    NaN    NaN  NaN     NaN   NaN   
4  Afganistán                AFG  1754     0    NaN    NaN  NaN     NaN   NaN   

  Otros Per Capita  
0   NaN        NaN  
1   NaN        NaN  
2   NaN        NaN  
3   NaN        NaN  
4   NaN        NaN

##**Desafío: leyendo datos de otro link**

####En este desafío, tu función es leer este link de Google Sheets y luego guardar el DataFrame obtenido en formato CSV. ¿Listo para comenzar?

In [59]:
sheet_id = '1QXLBXO_47wVw_snMFfL0OgcyZPJqN_KQy0OS6P4GTQc'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'


In [60]:
datos = pd.read_csv(url)
datos.head()

Country Name country_code                     Region  \
0        Aruba          ABW  Latin America & Caribbean   
1  Afghanistan          AFG                 South Asia   
2       Angola          AGO         Sub-Saharan Africa   
3      Albania          ALB      Europe & Central Asia   
4      Andorra          AND      Europe & Central Asia   

                           Indicator Name           1990         1991  \
0  CO2 emissions (metric tons per capita)            NaN          NaN   
1  CO2 emissions (metric tons per capita)    191.745.115  167.681.579   
2  CO2 emissions (metric tons per capita)    553.661.955  544.538.649   
3  CO2 emissions (metric tons per capita)  1.819.541.634  124.281.022   
4  CO2 emissions (metric tons per capita)  7.521.831.658  723.537.924   

          1992           1993           1994           1995  ...  \
0          NaN            NaN            NaN            NaN  ...   
1   95.957.742      8.472.111     75.545.827     68.467.956  ...   
2  543.557.223     70.898.423    836.804.405    912.141.485  ...   
3  683.699.826    638.307.036    645.355.189    605.436.253  ...   
4   69.630.787  6.724.177.518  6.541.578.914  6.733.479.486  ...   

            2011           2012           2013           2014           2015  \
0            NaN            NaN            NaN            NaN            NaN   
1     29.650.624    259.295.334     18.562.366    146.235.617    172.896.741   
2    985.522.312    950.695.879  1.036.293.852  1.099.779.111    113.504.405   
3    166.942.319    150.324.046  1.533.630.039  1.668.337.371    160.377.515   
4  5.850.886.105  5.944.654.173  5.942.800.412  5.807.127.723  6.026.181.822   

            2016           2017           2018           2019         2019.1  
0            NaN            NaN            NaN            NaN            NaN  
1    149.789.334    131.694.556      1.632.953    159.824.372    159.824.372  
2  1.031.811.348     81.330.073    777.674.934    792.137.069    792.137.069  
3  1.557.664.358  1.788.786.074  1.782.738.948    169.224.832    169.224.832  
4  6.080.600.282  6.104.133.912  6.362.975.399  6.481.217.432  6.481.217.432  

[5 rows x 35 columns]

###Guardando el archivo descargado y copiado en mi drive

In [61]:
datos.to_csv('datos_emisiones_co2.csv', index=False)

##**Lectura de datos en formato Json**

In [63]:
datos_pacientes = pd.read_json("/content/pacientes.json")

In [64]:
datos_pacientes

ID_paciente Enfermedad_corazon    IMC Fumador Consumo_alcohol AVC  \
0              0                 No  16.60      Sí              No  No   
1              1                 No  20.34      No              No  Sí   
2              2                 No  26.58      Sí              No  No   
3              3                 No  24.21      No              No  No   
4              4                 No  23.71      No              No  No   
..           ...                ...    ...     ...             ...  ..   
995          995                 No  28.29      Sí              No  No   
996          996                 No  25.69      Sí              No  No   
997          997                 Sí  26.99      No              No  No   
998          998                 No  44.29      No              No  No   
999          999                 No  25.83      No              No  No   

     Salud_fisica  Salud_mental Dificultad_caminar Sexo_biologico Rango_edad  \
0               3            30                 No       Femenino      55-59   
1               0             0                 No       Femenino     80 ó +   
2              20            30                 No      Masculino      65-69   
3               0             0                 No       Femenino      75-79   
4              28             0                 Sí       Femenino      40-44   
..            ...           ...                ...            ...        ...   
995            10            20                 No       Femenino      65-69   
996             0             0                 No       Femenino      75-79   
997             1             0                 No      Masculino      70-74   
998            30             0                 Sí       Femenino      70-74   
999             0             0                 No      Masculino      70-74   

       Raza Diabetes Actividad_fisica Salud_general  Horas_sueño Asma  \
0    Blanca       Sí               Sí     Muy buena            5   Sí   
1    Blanca       No               Sí     Muy buena            7   No   
2    Blanca       Sí               Sí     Razonable            8   Sí   
3    Blanca       No               No         Buena            6   No   
4    Blanca       No               Sí     Muy buena            8   No   
..      ...      ...              ...           ...          ...  ...   
995   Negra       Sí               Sí     Razonable            8   No   
996  Blanca       No               Sí     Excelente            8   No   
997  Blanca       No               Sí     Muy buena            8   No   
998  Blanca       Sí               No         Buena            6   Sí   
999   Negra       Sí               No     Excelente            7   No   

    Enfermedad_renal Cancer_piel  
0                 No          Sí  
1                 No          No  
2                 No          No  
3                 No          Sí  
4                 No          No  
..               ...         ...  
995               No          No  
996               No          No  
997               No          No  
998               No          No  
999               No          No  

[1000 rows x 19 columns]

In [66]:
datos_pacientes2 = pd.read_json("/content/pacientes_2.json")

In [67]:
datos_pacientes2

Investigación   Año  \
0  Indicadores clave de enfermedades cardíacas  2020   
1  Indicadores clave de enfermedades cardíacas  2020   
2  Indicadores clave de enfermedades cardíacas  2020   

                                           Pacientes  
0  {'ID': '01', 'Rango_edad': '55-59', 'Sexo_biol...  
1  {'ID': '02', 'Rango_edad': '80 ó +', 'Sexo_bio...  
2  {'ID': '03', 'Rango_edad': '65-69', 'Sexo_biol...

In [68]:
normalizado = pd.json_normalize(datos_pacientes2['Pacientes'])
normalizado

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]  
1     Muy buena            7                          [AVC]  
2     Muy buena            8               [Diabetes, Asma]

###**Para saber más: profundizando en la normalización**

####La normalización de datos es un proceso importante en la ciencia de datos que tiene como objetivo organizar y estandarizar datos para facilitar el análisis y la comparación entre ellos. Cuando se trata de datos en formato JSON (JavaScript Object Notation - Notación de objetos JavaScript), es común que estén anidados, lo que puede dificultar su análisis y manipulación.

####La biblioteca Pandas cuenta con una función llamada json_normalize() que permite la transformación de datos a formato tabular, facilitando la visualización y análisis de las informaciones. A continuación, aprenderemos cómo usar esta función para normalizar diferentes tipos de JSON en DataFrames.

####Normalizacion simple
A continuación tenemos una variable llamada datos y dentro de ella hay un objeto JSON con tres llaves y sus respectivos valores:

In [69]:
datos = {'Análisis': 'Principales indicadores de enfermedad cardíaca', 'Año': 2020, 'Numero_Pacientes':3}

Para normalizar esta variable, podemos pasarla dentro de la función json_normalize y analizar el DataFrame obtenido:

In [70]:
df = pd.json_normalize(datos)
df

Análisis   Año  Numero_Pacientes
0  Principales indicadores de enfermedad cardíaca  2020                 3

###**Normalizacion de Json con multiples niveles:**
Hay situaciones en las que el archivo JSON puede contener más de un objeto, como es el caso del siguiente ejemplo, en el que tenemos una lista, almacenada en la variable json_lista, que contiene dos objetos JSON:

In [71]:
json_lista = [
    { 'ID': '01', 'Intervalo_edad': '55-59', 'Sexo_biologico': 'femenino'},
    { 'ID': '02', 'Intervalo_edad': '80 ó +', 'Sexo_biologico': 'femenino'}
]

Para normalizar esta lista podemos aplicar la función json_normalize:

In [72]:
pd.json_normalize(json_lista)

ID Intervalo_edad Sexo_biologico
0  01          55-59       femenino
1  02         80 ó +       femenino

##**Normalizando un JSON con una lista anidada**

##Datos como un diccionario##

Iniciemos observando la normalización cuando los datos son un diccionario. Tenemos un diccionario almacenado en la variable json_obj. Observe que en la llave “Salud” tenemos otro diccionario:

In [73]:
json_obj = {
    'ID': '01',
    'Intervalo_edad': '55-59',
    'Sexo_biologico': 'Femenino',
    'Salud': {'Dificultad_caminar': 'No',
              'Actividad_fisica': 'Sí',
              'IMC': 16.6,
              'Enfermedad_cardiaca': 'No',
          }
      }

Haciendo la normalización:

In [74]:
pd.json_normalize(json_obj)

ID Intervalo_edad Sexo_biologico Salud.Dificultad_caminar  \
0  01          55-59       Femenino                       No   

  Salud.Actividad_fisica  Salud.IMC Salud.Enfermedad_cardiaca  
0                     Sí       16.6                        No

###Datos como una lista de diccionarios.

In [75]:
json_list = [
    {
    'ID': '01',
    'Intervalo_edad': '55-59',
    'Sexo_biologico': 'Femenino',
    'Salud': {'Dificultad_caminar': 'No',
              'Actividad_fisica': 'Sí',
              'IMC': 16.6,
              'Enfermedad_cardiaca': 'No',
          }
      },
      {
          'ID': '02',
          'Intervalo_edad': '80 ó +',
          'Sexo_biologico': 'Femenino',
          'Salud': {'Dificultad_caminar': 'No',
                    'Actividad_fisica': 'Sí',
                    'IMC': 20.34,
                    'Enfermedad_cardiaca': 'Sí'}
       }
       ]


Haciendo la normalización:

In [76]:
pd.json_normalize(json_list)

ID Intervalo_edad Sexo_biologico Salud.Dificultad_caminar  \
0  01          55-59       Femenino                       No   
1  02         80 ó +       Femenino                       No   

  Salud.Actividad_fisica  Salud.IMC Salud.Enfermedad_cardiaca  
0                     Sí      16.60                        No  
1                     Sí      20.34                        Sí

#####**Podemos ver que todos los valores anidados dentro de cada registro de la lista se han convertido en columnas separadas. ¿Qué pasa con los datos que normalizamos en el video anterior? ¿Recuerdas cómo su normalización se hizo de otra manera?**

#####**Resumiendo, vamos a copiar los datos del archivo paciente_2.json y vamos a guardarlos en una variable llamada datos_dict.**

In [77]:
datos_dict = {
  "Investigación": "Indicadores clave de enfermedades cardíacas",
  "Año": 2020,
  "Pacientes": [
    {
     "ID": "01",
      "Rango_edad": "55-59",
      "Sexo_biologico": "Mujer",
      "Raza": "Blanca",
      "IMC": 16.6,
      "Fumador": "Sí",
      "Consumo_alcohol": "No",
      "Salud_física": 3,
      "Salud_mental": 30,
      "Dificultad_caminar": "No",
      "Actividad_física": "Sí",
      "Salud_general": "Muy buena",
      "Horas_sueño": 5,
      "Problemas_salud": [
        "Diabetes",
        "Asma",
        "Cancer_piel"
      ]
    },
    {
      "ID": "02",
      "Rango_edad": "80 ó +",
      "Sexo_biologico": "Mujer",
      "Raza": "Blanca",
      "IMC": 20.34,
      "Fumador": "No",
      "Consumo_alcohol": "No",
      "Salud_física": 0,
      "Salud_mental": 0,
      "Dificultad_caminar": "No",
      "Actividad_física": "Sí",
      "Salud_general": "Muy buena",
      "Horas_sueño": 7,
      "Problemas_salud": [
        "AVC"
      ]
    },
    {
      "ID": "03",
      "Rango_edad": "65-69",
      "Sexo_biologico": "Masculino",
      "Raza": "Blanca",
      "IMC": 26.58,
      "Fumador": "Sí",
      "Consumo_alcohol": "No",
      "Salud_física": 20,
      "Salud_mental": 30,
      "Dificultad_caminar": "No",
      "Actividad_física": "Sí",
      "Salud_general": "Muy buena",
      "Horas_sueño": 8,
      "Problemas_salud": [
        "Diabetes",
        "Asma"
      ]
    }
  ]
}


##Si intentamos normalizar estos datos:

In [78]:
pd.json_normalize(datos_dict)

Investigación   Año  \
0  Indicadores clave de enfermedades cardíacas  2020   

                                           Pacientes  
0  [{'ID': '01', 'Rango_edad': '55-59', 'Sexo_bio...

#####Podemos observar que nuestra lista anidada está colocada en una única columna Pacientes. Entonces, usaremos el siguiente código para normalizar los datos, especificando qué columna está anidada:

In [79]:
pd.json_normalize(datos_dict['Pacientes'])

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]  
1     Muy buena            7                          [AVC]  
2     Muy buena            8               [Diabetes, Asma]

#####También podemos hacer esto usando el parámetro record_path como ['Pacientes']. Este parámetro se utiliza en la función pd.json_normalize() para especificar la ruta a los registros que deben ser normalizados en un DataFrame separado:

In [80]:
pd.json_normalize(datos_dict, record_path=['Pacientes'])

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]  
1     Muy buena            7                          [AVC]  
2     Muy buena            8               [Diabetes, Asma]

######El resultado parece excelente, pero no incluye las columnas "Investigación" y "Año". Para incluirlas, podemos usar el parámetro meta para especificar otras columnas que queramos en el DataFrame.

In [81]:
pd.json_normalize(
    datos_dict,
    record_path =['Pacientes'],
    meta=['Investigación', 'Año']
)

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  \
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]   
1     Muy buena            7                          [AVC]   
2     Muy buena            8               [Diabetes, Asma]   

                                 Investigación   Año  
0  Indicadores clave de enfermedades cardíacas  2020  
1  Indicadores clave de enfermedades cardíacas  2020  
2  Indicadores clave de enfermedades cardíacas  2020

####¡De esa manera tenemos todas las columnas presentes en el DataFrame!

#####Importante: En clase nosotros realizamos la normalización en un archivo con formato JSON. Sin embargo, la función json_normalize() sólo acepta un diccionario o una lista de diccionarios. Por esto, en el video se utilizó la estrategia de usar el código: pd.json_normalize(datos_pacientes_2['Pacientes']). Sin embargo, si intentamos utilizar parámetros de la función json_normalize en un archivo JSON, pueden surgir errores. Para solucionar esto, necesitamos importar el módulo json y leer los archivos según el siguiente código:

In [82]:
#Importando la biblioteca Pandas
import pandas as pd

#Importando el módulo JSON
import json

#Leyendo el archivo json usando el módulo Python JSON
with open('pacientes_2.json','r') as f:
    datos = json.loads(f.read())

#Normalizando los datos con los parámetros record_path y meta
pd.json_normalize(datos, record_path='Pacientes', meta=['Investigación', 'Año'])

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  \
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]   
1     Muy buena            7                          [AVC]   
2     Muy buena            8               [Diabetes, Asma]   

                                 Investigación   Año  
0  Indicadores clave de enfermedades cardíacas  2020  
1  Indicadores clave de enfermedades cardíacas  2020  
2  Indicadores clave de enfermedades cardíacas  2020

####**Y fue así que aprendimos cómo normalizar archivos JSON simples, con múltiples niveles y anidados.**

###**Exportar archivo Json**

In [83]:
#Importando la biblioteca Pandas
import pandas as pd

#Importando el módulo JSON
import json

#Leyendo el archivo json usando el módulo Python JSON
with open('pacientes_2.json','r') as f:
    datos = json.loads(f.read())

#Normalizando los datos con los parámetros record_path y meta
pd.json_normalize(datos, record_path='Pacientes', meta=['Investigación', 'Año'])

# Crear un DataFrame a partir de json_list
df_json_list = pd.DataFrame(json_list)

# Exportar el DataFrame a un archivo JSON
df_json_list.to_json('yo_asigno_este_nombre.json', index=False)

In [84]:
pd.read_json('yo_asigno_este_nombre.json')

ID Intervalo_edad Sexo_biologico  \
0   1          55-59       Femenino   
1   2         80 ó +       Femenino   

                                               Salud  
0  {'Dificultad_caminar': 'No', 'Actividad_fisica...  
1  {'Dificultad_caminar': 'No', 'Actividad_fisica...

##**Para Saber Mas:**
#####Para obtener datos en formato JSON podemos utilizar una API (Application Programming Interface). Es una interfaz de programación de aplicaciones que permite la comunicación entre diferentes programas o sistemas.

#####Hay varios formatos que se pueden utilizar en las API y uno de los más comunes es JSON (JavaScript Object Notation). JSON es un formato ligero para intercambiar información entre sistemas que utiliza la notación basada en objetos de JavaScript.

#####Tenemos la siguiente situación-problema:

#####“Una empresa de alimentos saludables tiene problemas con la popularidad de sus productos. A pesar de ofrecer opciones saludables, muchos clientes se muestran reacios a comprar los productos debido a la falta de información sobre los valores nutricionales de las frutas que se utilizan en la producción de alimentos”.

#####Ante esta situación podemos acceder a una API llamada Fruitvice para recopilar información detallada sobre los valores nutricionales de las frutas que se utilizan en los productos. Con esta información, la empresa podrá actualizar sus empaques y materiales de marketing para resaltar los valores nutricionales de las frutas y así atraer más clientes que buscan opciones saludables. Además, la empresa puede utilizar la información para desarrollar nuevos productos que satisfagan aún más las necesidades nutricionales de su clientela.

####Una forma común de acceder a las API es a través de la biblioteca requests. Para eso, también es necesario importar el módulo json:

In [9]:
import requests
import json

####Los datos de API Fruitvice se obtendrán con la función request.get('url'). Dentro de ella pasamos la dirección API seguida de api/fruit/all para obtener los datos de todas las frutas.

In [10]:
datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')

####Conseguimos recuperar los resultados utilizando la función json.loads(). Para ello es necesario pasar la variable datos_frutas, previamente creada con el atributo text que devuelve el contenido de la respuesta.

In [11]:
resultado = json.loads(datos_frutas.text)

####Luego podemos obtener una vista previa del DataFrame.

In [12]:
pd.DataFrame(resultado)

name   id           family             order         genus  \
0            Persimmon   52        Ebenaceae           Rosales     Diospyros   
1           Strawberry    3         Rosaceae           Rosales      Fragaria   
2               Banana    1         Musaceae      Zingiberales          Musa   
3               Tomato    5       Solanaceae         Solanales       Solanum   
4                 Pear    4         Rosaceae           Rosales         Pyrus   
5               Durian   60        Malvaceae          Malvales         Durio   
6           Blackberry   64         Rosaceae           Rosales         Rubus   
7          Lingonberry   65        Ericaceae          Ericales     Vaccinium   
8                 Kiwi   66    Actinidiaceae  Struthioniformes       Apteryx   
9               Lychee   67      Sapindaceae        Sapindales        Litchi   
10           Pineapple   10     Bromeliaceae            Poales        Ananas   
11                 Fig   68         Moraceae           Rosales         Ficus   
12          Gooseberry   69  Grossulariaceae      Saxifragales         Ribes   
13        Passionfruit   70   Passifloraceae      Malpighiales    Passiflora   
14                Plum   71         Rosaceae           Rosales        Prunus   
15              Orange    2         Rutaceae        Sapindales        Citrus   
16          GreenApple   72         Rosaceae           Rosales         Malus   
17           Raspberry   23         Rosaceae           Rosales         Rubus   
18          Watermelon   25    Cucurbitaceae      Cucurbitales     Citrullus   
19               Lemon   26         Rutaceae        Sapindales        Citrus   
20               Mango   27    Anacardiaceae        Sapindales     Mangifera   
21           Blueberry   33         Rosaceae           Rosales      Fragaria   
22               Apple    6         Rosaceae           Rosales         Malus   
23               Guava   37        Myrtaceae          Myrtales       Psidium   
24             Apricot   35         Rosaceae           Rosales        Prunus   
25               Melon   41    Cucurbitaceae     Cucurbitaceae       Cucumis   
26           Tangerine   77         Rutaceae        Sapindales        Citrus   
27            Pitahaya   78        Cactaceae    Caryophyllales     Cactaceae   
28                Lime   44         Rutaceae        Sapindales        Citrus   
29         Pomegranate   79       Lythraceae          Myrtales        Punica   
30         Dragonfruit   80        Cactaceae    Caryophyllales  Selenicereus   
31               Grape   81         Vitaceae           Vitales         Vitis   
32               Morus   82         Moraceae           Rosales         Morus   
33              Feijoa   76        Myrtaceae        Myrtoideae    Sellowiana   
34             Avocado   84        Lauraceae          Laurales        Persea   
35           Kiwifruit   85    Actinidiaceae          Ericales     Actinidia   
36           Cranberry   87        Ericaceae          Ericales     Vaccinium   
37              Cherry    9         Rosaceae           Rosales        Prunus   
38               Peach   86         Rosaceae           Rosales        Prunus   
39           Jackfruit   94         Moraceae           Rosales    Artocarpus   
40        Horned Melon   95    Cucurbitaceae      Cucurbitales       Cucumis   
41            Hazelnut   96       Betulaceae           Fagales       Corylus   
42              Pomelo   98         Rutaceae        Sapindales        Citrus   
43          Mangosteen   99       Clusiaceae      Malpighiales      Garcinia   
44             Pumpkin  100    Cucurbitaceae      Cucurbitales     Cucurbita   
45  Japanese Persimmon  101        Ebenaceae          Ericales     Diospyros   
46              Papaya   42       Caricaceae       Brassicales        Carica   
47              Annona  103       Annonaceae           Rosales       Annonas   
48   Ceylon Gooseberry  104       Salicaceae      Malpighiales      Dovyalis   

                 

####¡Ahora sabemos cómo utilizar la biblioteca requests y el módulo JSON para obtener datos de las API!

##**Desafio**

Es el momento de poner a prueba tus conocimientos adquiridos durante la clase. El DataFrame que se muestra a continuación se generó después de obtener los datos de la API de Fruitvice:
Este DataFrame tiene 6 columnas: genus (género), name (nombre), id, family (familia), order (orden) e nutritions (nutriciones). Observe que la columna nutritions tiene toda la información nutricional anidada en ella. Por tanto, es necesario normalizar los datos.

El desafío ahora es normalizar este DataFrame.

In [13]:
import requests
import json

datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')
resultado = json.loads(datos_frutas.text)

In [14]:
import pandas as pd
datos_frutas_normalizado = pd.json_normalize(resultado)

In [15]:
datos_frutas_normalizado

name   id           family             order         genus  \
0            Persimmon   52        Ebenaceae           Rosales     Diospyros   
1           Strawberry    3         Rosaceae           Rosales      Fragaria   
2               Banana    1         Musaceae      Zingiberales          Musa   
3               Tomato    5       Solanaceae         Solanales       Solanum   
4                 Pear    4         Rosaceae           Rosales         Pyrus   
5               Durian   60        Malvaceae          Malvales         Durio   
6           Blackberry   64         Rosaceae           Rosales         Rubus   
7          Lingonberry   65        Ericaceae          Ericales     Vaccinium   
8                 Kiwi   66    Actinidiaceae  Struthioniformes       Apteryx   
9               Lychee   67      Sapindaceae        Sapindales        Litchi   
10           Pineapple   10     Bromeliaceae            Poales        Ananas   
11                 Fig   68         Moraceae           Rosales         Ficus   
12          Gooseberry   69  Grossulariaceae      Saxifragales         Ribes   
13        Passionfruit   70   Passifloraceae      Malpighiales    Passiflora   
14                Plum   71         Rosaceae           Rosales        Prunus   
15              Orange    2         Rutaceae        Sapindales        Citrus   
16          GreenApple   72         Rosaceae           Rosales         Malus   
17           Raspberry   23         Rosaceae           Rosales         Rubus   
18          Watermelon   25    Cucurbitaceae      Cucurbitales     Citrullus   
19               Lemon   26         Rutaceae        Sapindales        Citrus   
20               Mango   27    Anacardiaceae        Sapindales     Mangifera   
21           Blueberry   33         Rosaceae           Rosales      Fragaria   
22               Apple    6         Rosaceae           Rosales         Malus   
23               Guava   37        Myrtaceae          Myrtales       Psidium   
24             Apricot   35         Rosaceae           Rosales        Prunus   
25               Melon   41    Cucurbitaceae     Cucurbitaceae       Cucumis   
26           Tangerine   77         Rutaceae        Sapindales        Citrus   
27            Pitahaya   78        Cactaceae    Caryophyllales     Cactaceae   
28                Lime   44         Rutaceae        Sapindales        Citrus   
29         Pomegranate   79       Lythraceae          Myrtales        Punica   
30         Dragonfruit   80        Cactaceae    Caryophyllales  Selenicereus   
31               Grape   81         Vitaceae           Vitales         Vitis   
32               Morus   82         Moraceae           Rosales         Morus   
33              Feijoa   76        Myrtaceae        Myrtoideae    Sellowiana   
34             Avocado   84        Lauraceae          Laurales        Persea   
35           Kiwifruit   85    Actinidiaceae          Ericales     Actinidia   
36           Cranberry   87        Ericaceae          Ericales     Vaccinium   
37              Cherry    9         Rosaceae           Rosales        Prunus   
38               Peach   86         Rosaceae           Rosales        Prunus   
39           Jackfruit   94         Moraceae           Rosales    Artocarpus   
40        Horned Melon   95    Cucurbitaceae      Cucurbitales       Cucumis   
41            Hazelnut   96       Betulaceae           Fagales       Corylus   
42              Pomelo   98         Rutaceae        Sapindales        Citrus   
43          Mangosteen   99       Clusiaceae      Malpighiales      Garcinia   
44             Pumpkin  100    Cucurbitaceae      Cucurbitales     Cucurbita   
45  Japanese Persimmon  101        Ebenaceae          Ericales     Diospyros   
46              Papaya   42       Caricaceae       Brassicales        Carica   
47              Annona  103       Annonaceae           Rosales       Annonas   
48   Ceylon Gooseberry  104       Salicaceae      Malpighiales      Dovyalis   

    nutritions.ca

##**Importando Pàginas Web**


In [16]:
import pandas as pd


In [85]:
datos_html = pd.read_html("/content/peliculas_wikipedia.html")

In [86]:
datos_html

[       0                      1
 0   1998             100 Movies
 1   1999              100 Stars
 2   2000             100 Laughs
 3   2001            100 Thrills
 4   2002           100 Passions
 5   2003  100 Heroes & Villains
 6   2004              100 Songs
 7   2005       100 Movie Quotes
 8   2005              25 Scores
 9   2006             100 Cheers
 10  2006            25 Musicals
 11  2007   100 Movies (Updated)
 12  2008        AFI's 10 Top 10
 13   vte                    vte,
                             Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles   
 1                     Casablanca          1942        Michael Curtiz   
 2                  The Godfather          1972  Francis Ford Coppola   
 3             Gone with the Wind          1939        Victor Fleming   
 4             Lawrence of Arabia          1962            David Lean   
 ..                           ...           ...                   

In [87]:
type(datos_html)

list

In [88]:
len(datos_html)

3

In [89]:
top_peliculas = datos_html[1]

In [90]:
top_peliculas

Film  Release year              Director  \
0                   Citizen Kane          1941          Orson Welles   
1                     Casablanca          1942        Michael Curtiz   
2                  The Godfather          1972  Francis Ford Coppola   
3             Gone with the Wind          1939        Victor Fleming   
4             Lawrence of Arabia          1962            David Lean   
..                           ...           ...                   ...   
95                 The Searchers          1956             John Ford   
96              Bringing Up Baby          1938          Howard Hawks   
97                    Unforgiven          1992        Clint Eastwood   
98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
99           Yankee Doodle Dandy          1942        Michael Curtiz   

                      Production companies  Rank  
0                       RKO Radio Pictures     1  
1                    Warner Bros. Pictures     2  
2   Paramount Pictures, Alfran Productions     3  
3          Selznick International Pictures     4  
4                         Horizon Pictures     5  
..                                     ...   ...  
95                  C. V. Whitney Pictures    96  
96                      RKO Radio Pictures    97  
97                     The Malpaso Company    98  
98                       Columbia Pictures    99  
99                   Warner Bros. Pictures   100  

[100 rows x 5 columns]

In [91]:
top_peliculas.to_html('top_peliculas.html', index=False)

In [92]:
pd.read_html('/content/top_peliculas.html')

[                            Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles   
 1                     Casablanca          1942        Michael Curtiz   
 2                  The Godfather          1972  Francis Ford Coppola   
 3             Gone with the Wind          1939        Victor Fleming   
 4             Lawrence of Arabia          1962            David Lean   
 ..                           ...           ...                   ...   
 95                 The Searchers          1956             John Ford   
 96              Bringing Up Baby          1938          Howard Hawks   
 97                    Unforgiven          1992        Clint Eastwood   
 98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
 99           Yankee Doodle Dandy          1942        Michael Curtiz   
 
                       Production companies  Rank  
 0                       RKO Radio Pictures     1  
 1                

In [93]:
top_peliculas.to_csv('top_peliculas_1998.csv', index=False)

In [94]:
datos = pd.read_csv('/content/top_peliculas_1998.csv')
datos.head()

Film  Release year              Director  \
0        Citizen Kane          1941          Orson Welles   
1          Casablanca          1942        Michael Curtiz   
2       The Godfather          1972  Francis Ford Coppola   
3  Gone with the Wind          1939        Victor Fleming   
4  Lawrence of Arabia          1962            David Lean   

                     Production companies  Rank  
0                      RKO Radio Pictures     1  
1                   Warner Bros. Pictures     2  
2  Paramount Pictures, Alfran Productions     3  
3         Selznick International Pictures     4  
4                        Horizon Pictures     5

##**Importando Informacion en HTML**

In [95]:
import pandas as pd

In [97]:
datos_xml = pd.read_xml('/content/imdb_top_1000.xml')

In [100]:
datos_xml.head(3)

index                                        Poster_Link  \
0      0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1      1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2      2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   

            Star4  No_of_Votes        Gross  
0  William Sadler      2343110   28,341,469  
1    Diane Keaton      1620367  134,966,411  
2   Michael Caine      2303232  534,858,444

In [102]:
#se puede guardar en el tipo de archivo que uno prefiera en este caso de Html A Csv.
datos_xml.to_csv('datos_xml.csv', index=False)

##**Desafío: leer una tabla de una página web**

In [105]:
pd.read_html('https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n')[0]

N.º                   País (o territorio dependiente)  \
0      1                                             India   
1      2                                        China[12]​   
2      3                                    Estados Unidos   
3      4                                         Indonesia   
4      5                                          Pakistán   
..   ...                                               ...   
241  242                           Islas Cocos (Australia)   
242  243  Islas Ultramarinas Menores de los Estados Unidos   
243  244                               Islas Pitcairn (RU)   
244  NaN                                             Mundo   
245   N°                   País (o territorio dependiente)   

    Proyección exponencial de la población al 1/7/2025[7]​  \
0                                        1 417 492 000       
1                                        1 407 934 000       
2                                          342 181 000       
3                                          285 783 000       
4                                          256 204 000       
..                                                 ...       
241                                                600       
242                                                100       
243                                                 30       
244                                      8 083 454 000       
245  Proyección exponencial de la población al 1/7/...       

     Total mun- dial (%) Cambio medio anual (%)[8]​  \
0                   1754                        090   
1                   1742                       -005   
2                    423                        061   
3                    354                        117   
4                    317                        256   
..                   ...                        ...   
241                  000                        174   
242                  000                       -496   
243                  000                       -111   
244                10000                        103   
245  Total mun- dial (%)     Cambio medio anual (%)   

     Cambio absoluto anual promedio  Cambio medio abs. total anual (%)  \
0                        12 692 000                               1523   
1                        -1 390 000                                  -   
2                         2 084 000                                250   
3                         3 337 000                                400   
4                         6 567 000                                788   
..                              ...                                ...   
241                               0                                000   
242                               0                                000   
243                               0                                000   
244                      83 361 000                              10000   
245  Cambio absoluto anual promedio  Cambio medio abs. total anual (%)   

    Años para even- tual du- pli- ca- ción[9]​  \
0                                           78   
1                                            -   
2                                          114   
3                                           60   
4                                           27   
..                                         ...   
241                                         40   
242                                          -   
243                                          -   
244                                         68   
245     Años para even- tual du- pli- ca- ción   

    Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional  \
0                                        1 417 492 000                                                  
1                                        1 408 280 000                                                  
2                                          341 76

##**Creando un bancos de datos local**

In [106]:
import sqlalchemy

In [109]:
from sqlalchemy import create_engine, MetaData, Table, inspect, Column, Integer, String, Text

In [110]:
engine = create_engine('sqlite:///:memory:')

###Para saber más: bases de datos y SQLAlchemy

Las bases de datos son sistemas que permiten el almacenamiento, organización y recuperación de información de forma estructurada y eficiente. Se utilizan ampliamente en muchas áreas, desde la gestión empresarial hasta la investigación científica. Una base de datos bien diseñada puede mejorar significativamente la eficiencia y precisión de las operaciones de una organización.

Existen bases de datos relacionales y no relacionales. Las bases de datos relacionales representan y almacenan datos en tablas. Las bases de datos no relacionales, también conocidas como bases de datos NoSQL (Not Only SQL - No Sólo SQL), utilizan una variedad de estructuras de datos, como documentos, gráfos o pares llave-valor.

Python ofrece varios paquetes y bibliotecas para trabajar con bases de datos, incluyendo SQLite, MySQL, PostgreSQL, Oracle, MongoDB, entre otros. Uno de los paquetes más comunes utilizados para trabajar con bases de datos relacionales en Python es el paquete sqlite3 que ofrece soporte a bases de datos SQLite. Esta base de datos es liviana e integrada, no requiere un servidor separado para ejecutarse y está instalada de forma nativa en Google Colab.

Para trabajar con esta base de datos, podemos usar SQLAlchemy, una biblioteca de mapeo objeto-relacional (ORM), que permite interactuar con bases de datos relacionales usando código Python. Proporciona una capa de abstracción que permite a los desarrolladores trabajar con objetos Python en lugar de lidiar directamente con las complejidades del lenguaje SQL (Structured Query Language - Lenguaje de consulta estructurado).

Uno de los principales beneficios de utilizar SQLAchemy es la capacidad de crear código más legible y fácil de mantener. Con SQLAlchemy, las operaciones de la base de datos se realizan utilizando métodos en objetos Python, lo que hace que el código sea más claro y menos propenso a errores.

Además, SQLAlchemy ofrece soporte a consultas complejas en bases de datos, lo que permite a los desarrolladores extraer fácilmente información relevante de grandes conjuntos de datos. Esto es especialmente útil en aplicaciones que necesitan manejar grandes cantidades de datos.

##**Escribiendo una base de datos**

In [111]:
import pandas as pd

In [115]:
archivo = '/content/clientes_banco.csv'

In [116]:
datos = pd.read_csv(archivo)

In [117]:
datos.head()

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0     5008804    32    Nivel superior  Relación-estable               2   
1     5008805    32    Nivel superior  Relación-estable               2   
2     5008806    58  Nivel intermedio            Casado               2   
3     5008808    52  Nivel intermedio           Soltero               1   
4     5008809    52  Nivel intermedio           Soltero               1   

  Categoria_de_renta  Ocupacion  Años_empleado  Rendimiento_anual  \
0           Empleado       Otro             12           427500.0   
1           Empleado       Otro             12           427500.0   
2           Empleado  Seguridad              3           112500.0   
3   Business Partner     Ventas              8           270000.0   
4   Business Partner     Ventas              8           270000.0   

   Tiene_carro                  Vivienda  
0            1    Departamento alquilado  
1            1    Departamento alquilado  
2            1  Casa/Departamento propio  
3            0  Casa/Departamento propio  
4            0  Casa/Departamento propio

In [118]:
datos.to_sql('clientes', engine, index = False)

438463

In [119]:
#debe ser este nombre por convensión de python y libreria
inspector = inspect(engine)

In [120]:
print(inspector.get_table_names())

['clientes']


##**Leyendo consultas en SQL**

In [122]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renta = "Empleado"'

In [126]:
from sqlalchemy import text # Import the text construct

empleados = pd.read_sql(sql=text(query), con=engine.connect()) # Call the connect() method

In [127]:
empleados

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008815    46    Nivel superior            Casado               2   
4          5112956    46    Nivel superior            Casado               2   
...            ...   ...               ...               ...             ...   
226054     6837905    43  Nivel intermedio            Casado               3   
226055     6837906    43  Nivel intermedio            Casado               3   
226056     6839936    34  Nivel intermedio            Casado               3   
226057     6840222    43  Nivel intermedio           Soltero               1   
226058     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3                Empleado        Contabilidad              2   
4                Empleado        Contabilidad              2   
...                   ...                 ...            ...   
226054           Empleado                Otro              7   
226055           Empleado                Otro              7   
226056           Empleado  Construcción Civil              5   
226057           Empleado  Construcción Civil              8   
226058           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            1  Casa/Departamento propio  
4                270000.0            1  Casa/Departamento propio  
...                   ...          ...                       ...  
226054           355050.0            1  Casa/Departamento propio  
226055           355050.0            1  Casa/Departamento propio  
226056           135000.0            1  Casa/Departamento propio  
226057           103500.0            0  Casa/Departamento propio  
226058           121500.0            0  Casa/Departamento propio  

[226059 rows x 11 columns]

In [128]:
empleados.to_sql('empleados', con = engine.connect(), index=False)

226059

In [133]:
#Leer la nueva tabla creada
pd.read_sql_table('empleados', con = engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008815    46    Nivel superior            Casado               2   
4          5112956    46    Nivel superior            Casado               2   
...            ...   ...               ...               ...             ...   
226054     6837905    43  Nivel intermedio            Casado               3   
226055     6837906    43  Nivel intermedio            Casado               3   
226056     6839936    34  Nivel intermedio            Casado               3   
226057     6840222    43  Nivel intermedio           Soltero               1   
226058     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3                Empleado        Contabilidad              2   
4                Empleado        Contabilidad              2   
...                   ...                 ...            ...   
226054           Empleado                Otro              7   
226055           Empleado                Otro              7   
226056           Empleado  Construcción Civil              5   
226057           Empleado  Construcción Civil              8   
226058           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            1  Casa/Departamento propio  
4                270000.0            1  Casa/Departamento propio  
...                   ...          ...                       ...  
226054           355050.0            1  Casa/Departamento propio  
226055           355050.0            1  Casa/Departamento propio  
226056           135000.0            1  Casa/Departamento propio  
226057           103500.0            0  Casa/Departamento propio  
226058           121500.0            0  Casa/Departamento propio  

[226059 rows x 11 columns]

In [132]:
#Para selecionar algunas columnas
pd.read_sql_table('empleados', con = engine.connect(), columns=['ID_Cliente', 'Edad', 'Años_empleado'])

ID_Cliente  Edad  Años_empleado
0          5008804    32             12
1          5008805    32             12
2          5008806    58              3
3          5008815    46              2
4          5112956    46              2
...            ...   ...            ...
226054     6837905    43              7
226055     6837906    43              7
226056     6839936    34              5
226057     6840222    43              8
226058     6842885    51              3

[226059 rows x 3 columns]

##**Actualizando una base de datos**

In [134]:
query = 'SELECT * FROM clientes'

In [135]:
pd.read_sql(sql=text(query), con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008809    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840104    62  Nivel intermedio        Divorciado               1   
438459     6840222    43  Nivel intermedio           Soltero               1   
438460     6841878    22    Nivel superior           Soltero               1   
438461     6842765    59  Nivel intermedio            Casado               2   
438462     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458        Pensionista                Otro              0   
438459           Empleado  Construcción Civil              8   
438460   Business Partner              Ventas              1   
438461        Pensionista                Otro              0   
438462           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           135000.0            0  Casa/Departamento propio  
438459           103500.0            0  Casa/Departamento propio  
438460            54000.0            0       Vive con los padres  
438461            72000.0            0  Casa/Departamento propio  
438462           121500.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]

In [138]:
#Borrando registros
from sqlalchemy.exc import SQLAlchemyError
query = 'DELETE FROM clientes WHERE ID_Cliente = 5008804'
try:
    r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
    print("#Registros Borrados: ", r_set.rowcount)

#Registros Borrados:  1


In [142]:
pd.read_sql_table('clientes', con = engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008805    32    Nivel superior  Relación-estable               2   
1          5008806    58  Nivel intermedio            Casado               2   
2          5008808    52  Nivel intermedio           Soltero               1   
3          5008809    52  Nivel intermedio           Soltero               1   
4          5008810    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438457     6840104    62  Nivel intermedio        Divorciado               1   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado           Seguridad              3   
2        Business Partner              Ventas              8   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438457        Pensionista                Otro              0   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                112500.0            1  Casa/Departamento propio  
2                270000.0            0  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438457           135000.0            0  Casa/Departamento propio  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  

[438462 rows x 11 columns]

In [143]:
#Actualizando registros

query = "UPDATE clientes SET Grado_estudio='Nivel superior' WHERE ID_Cliente=5008808"
try:
    r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
    print("#Registros Actualizados: ", r_set.rowcount)

#Registros Actualizados:  1


In [144]:
pd.read_sql_table('clientes', con = engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008805    32    Nivel superior  Relación-estable               2   
1          5008806    58  Nivel intermedio            Casado               2   
2          5008808    52    Nivel superior           Soltero               1   
3          5008809    52  Nivel intermedio           Soltero               1   
4          5008810    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438457     6840104    62  Nivel intermedio        Divorciado               1   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado           Seguridad              3   
2        Business Partner              Ventas              8   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438457        Pensionista                Otro              0   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                112500.0            1  Casa/Departamento propio  
2                270000.0            0  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438457           135000.0            0  Casa/Departamento propio  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  

[438462 rows x 11 columns]

In [145]:
inspector = inspect(engine)
print(inspector.get_table_names())

['clientes', 'empleados']


##**Desafío: manipulando una base de datos**

##Tu misión es:

Crear la base de datos local con la biblioteca SQLAlchemy.
Escribir los datos del archivo CSV en esta base de datos local.
Realizar tres actualizaciones en la base de datos:
Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000.
Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene cuenta en la institución financiera.
Crear un nuevo registro de cliente siguiendo las especificaciones a continuación:
ID_cliente: 6850985
Edad: 33
Grado_estudio: Doctorado
Estado_civil: Soltero
Tamaño_familia: 1
Categoria_de_renta: Empleado
Ocupacion: TI
Años_empleado: 2
Rendimiento_anual: 290000
Tiene_carro: 0
Vivienda: Casa/Departamento propio
Consejo importante: Para agregar un nuevo cliente a la tabla, use la cláusula INSERT INTO seguida del nombre de la tabla y luego especifique los nombres de las columnas de la tabla entre paréntesis. Utilice la cláusula VALUES y luego pase entre paréntesis los nuevos valores para este nuevo registro. Asegúrese de que los valores estén en el orden correcto y en el formato adecuado para cada columna.

##**Opinion del instructor**

Para crear la base de datos local es necesario ejecutar los siguientes comandos. Este código consiste en importar la biblioteca sqlalchemy y crear un objeto engine que representa una conexión a una base de datos SQLite en memoria. El método create_engine se utiliza para crear el objeto engine y especificar la base de datos que se utilizará. En este caso, la base de datos es una base de datos SQLite en memoria, que se crea usando sqlite:///:memory::

In [146]:
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text
engine = create_engine('sqlite:///:memory:')

A continuación, podemos leer los datos con la función read_csv y escribirlos en el formato de la base de datos con la función to_sql:

In [147]:
import pandas as pd
archivo = 'clientes_banco.csv'
datos = pd.read_csv(archivo)
datos.to_sql('clientes', engine, index=False)

383224

Después de crear la tabla, podemos obtener un DataFrame con la función read_sql_table:

In [148]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804  32.0    Nivel superior  Relación-estable             2.0   
1          5008805  32.0    Nivel superior  Relación-estable             2.0   
2          5008806  58.0  Nivel intermedio            Casado             2.0   
3          5008808  52.0  Nivel intermedio           Soltero             1.0   
4          5008809  52.0  Nivel intermedio           Soltero             1.0   
...            ...   ...               ...               ...             ...   
383219     6689092  57.0    Nivel superior            Casado             2.0   
383220     6689093  57.0    Nivel superior            Casado             2.0   
383221     6618205  52.0  Nivel intermedio  Relación-estable             2.0   
383222     6690761  52.0  Nivel intermedio  Relación-estable             2.0   
383223          66   NaN              None              None             NaN   

       Categoria_de_renta         Ocupacion  Años_empleado  Rendimiento_anual  \
0                Empleado              Otro           12.0           427500.0   
1                Empleado              Otro           12.0           427500.0   
2                Empleado         Seguridad            3.0           112500.0   
3        Business Partner            Ventas            8.0           270000.0   
4        Business Partner            Ventas            8.0           270000.0   
...                   ...               ...            ...                ...   
383219   Business Partner          Gerencia           15.0           189000.0   
383220   Business Partner          Gerencia           15.0           189000.0   
383221           Empleado  Equipo principal            2.0            90000.0   
383222           Empleado  Equipo principal            2.0            90000.0   
383223               None              None            NaN                NaN   

        Tiene_carro                  Vivienda  
0               1.0    Departamento alquilado  
1               1.0    Departamento alquilado  
2               1.0  Casa/Departamento propio  
3               0.0  Casa/Departamento propio  
4               0.0  Casa/Departamento propio  
...             ...                       ...  
383219          1.0  Casa/Departamento propio  
383220          1.0  Casa/Departamento propio  
383221          0.0  Casa/Departamento propio  
383222          0.0  Casa/Departamento propio  
383223          NaN                      None  

[383224 rows x 11 columns]

¡Ahora vamos a comenzar las actualizaciones de la base de datos!

Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000:

El siguiente código actualiza el rendimiento anual del ID de cliente 6840104 en la tabla clientes. La variable query contiene una declaración SQL que actualiza ese registro. Luego, la declaración engine.connect() se usa para crear una conexión a la base de datos SQLite. Finalmente, la declaración .execute(text(query)) se utiliza para ejecutar la declaración SQL contenida en la variable query y actualizar el registro en la tabla clientes.

In [149]:
from sqlalchemy.exc import SQLAlchemyError
query = 'UPDATE clientes SET Rendimiento_anual=300000.0 WHERE ID_Cliente=6840104'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros actualizados: ",r_set.rowcount)

#Registros actualizados:  0


Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene una cuenta en la institución financiera:



In [151]:
from sqlalchemy.exc import SQLAlchemyError
query = 'DELETE FROM clientes WHERE ID_Cliente=5008809'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros borrados: ",r_set.rowcount)

#Registros borrados:  1


Cree un nuevo registro de cliente siguiendo las especificaciones dadas anteriormente:

Al trabajar con bases de datos, es común necesitar insertar nuevos registros en nuestras tablas. Para ello podemos utilizar la cláusula INSERT INTO que nos permite añadir nuevos datos de forma práctica y rápida.

Para utilizar esta cláusula, primero debe especificar el nombre de la tabla en la que se insertará el registro. A continuación, debemos pasar entre paréntesis los nombres de las columnas donde se agregarán los nuevos valores. Es importante recordar que el orden de los nombres debe ser el mismo orden en el que se pasarán los valores.

Después de especificar las columnas, usamos la cláusula VALUES para agregar los nuevos valores. Nuevamente debemos pasar entre paréntesis los valores a insertar en el mismo orden en que se especificaron las columnas. Es importante asegurarse de que los valores estén en el formato correcto para cada tipo de datos.

Como la `query` es larga, puedes usar `' \` para indicar que el código continúa en la siguiente línea.

In [152]:
from sqlalchemy.exc import SQLAlchemyError
query = 'INSERT INTO clientes (ID_Cliente, Edad, Grado_estudio, Estado_civil, ' \
        'Tamaño_familia, Categoria_de_renta, Ocupacion, Años_empleado, ' \
        'Rendimiento_anual, Tiene_carro, Vivienda) ' \
        'VALUES (6850985, 33, "Doctorado", "Soltero", 1, "Empleado", "TI", ' \
        '2, 290000, 0, "Casa/Departamento propio")'

try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros insertados: ",r_set.rowcount)

#Registros insertados:  1


Para verificar que se realizaron los cambios, puede leer la tabla con el siguiente código:

In [153]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804  32.0    Nivel superior  Relación-estable             2.0   
1          5008805  32.0    Nivel superior  Relación-estable             2.0   
2          5008806  58.0  Nivel intermedio            Casado             2.0   
3          5008808  52.0  Nivel intermedio           Soltero             1.0   
4          5008810  52.0  Nivel intermedio           Soltero             1.0   
...            ...   ...               ...               ...             ...   
383219     6689093  57.0    Nivel superior            Casado             2.0   
383220     6618205  52.0  Nivel intermedio  Relación-estable             2.0   
383221     6690761  52.0  Nivel intermedio  Relación-estable             2.0   
383222          66   NaN              None              None             NaN   
383223     6850985  33.0         Doctorado           Soltero             1.0   

       Categoria_de_renta         Ocupacion  Años_empleado  Rendimiento_anual  \
0                Empleado              Otro           12.0           427500.0   
1                Empleado              Otro           12.0           427500.0   
2                Empleado         Seguridad            3.0           112500.0   
3        Business Partner            Ventas            8.0           270000.0   
4        Business Partner            Ventas            8.0           270000.0   
...                   ...               ...            ...                ...   
383219   Business Partner          Gerencia           15.0           189000.0   
383220           Empleado  Equipo principal            2.0            90000.0   
383221           Empleado  Equipo principal            2.0            90000.0   
383222               None              None            NaN                NaN   
383223           Empleado                TI            2.0           290000.0   

        Tiene_carro                  Vivienda  
0               1.0    Departamento alquilado  
1               1.0    Departamento alquilado  
2               1.0  Casa/Departamento propio  
3               0.0  Casa/Departamento propio  
4               0.0  Casa/Departamento propio  
...             ...                       ...  
383219          1.0  Casa/Departamento propio  
383220          0.0  Casa/Departamento propio  
383221          0.0  Casa/Departamento propio  
383222          NaN                      None  
383223          0.0  Casa/Departamento propio  

[383224 rows x 11 columns]

¡Misión completada con éxito!